Default mix text cases to number of CPUs
This changes the mix test default which is 2 x number of CPUs.

We only append --trace if VERBOSE_TEST is true (enabled by default) and
don't change the number of max-cases. I'm not sure why we coupled the
number of max cases to verbose testing, they don't seem related to me.
Since @dfedotov is no longer with us, I can't ask him, so just making
the change which feels right.

This is in response to GitHub Actions failing consistently with:

    == Compilation error in file test/ctl/list_connections_command_test.exs ==
    ** (exit) exited in: :gen_server.call(#PID<32153.2990.0>, {:read_cache, -576460752303386991}, :infinity)
        ** (EXIT) no connection to rabbit_ctl_36@fv-az56
    ##[error]    (stdlib 3.8) gen_server.erl:223: :gen_server.call/3
    ##[error]    (stdlib 3.8) erl_eval.erl:680: :erl_eval.do_apply/6
    ##[error]    (stdlib 3.8) erl_eval.erl:888: :erl_eval.expr_list/6
    ##[error]    (stdlib 3.8) erl_eval.erl:411: :erl_eval.expr/5
    ##[error]    (elixir 1.10.2) lib/kernel/parallel_compiler.ex:396: Kernel.ParallelCompiler.require_file/2
    ##[error]    (elixir 1.10.2) lib/kernel/parallel_compiler.ex:306: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
    ##[error]Makefile:114: recipe for target 'tests' failed

Our assumption is that limiting the number of test parallelism will make
these failures go away.

cc @michaelklishin @dumbbell

Signed-off-by: Gerhard Lazu <gerhard@lazu.co.uk>